"""Add client_name and client_contact to Event model

Revision ID: 66f565a08ce8
Revises: 2280a5feb35f
Create Date: 2025-04-07 15:11:25.107280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66f565a08ce8'
down_revision: Union[str, None] = '2280a5feb35f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('client_name', sa.String(), nullable=True))
    op.add_column('events', sa.Column('client_contact', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'client_contact')
    op.drop_column('events', 'client_name')
    # ### end Alembic commands ###
